AWSTemplateFormatVersion: "2010-09-09"

Description:
    AWS Demo Lambda.
    
Resources:
    lambdarole:
        Type: 'AWS::IAM::Role'
        Properties: 
            "Service": "lambda.amazonaws.com"
        Action: "sts:AssumeRole"

